from Sumi import DEV_USERS, SUDO_USERS, SUPPORT_USERS, WHITELIST_USERS, telethn

ISHIKKI = 5283999496

IMMUNE_USERS = SUDO_USERS + WHITELIST_USERS + SUPPORT_USERS + DEV_USERS + ISHIKKI

IMMUNE_USERS = list(SUDO_USERS) + list(WHITELIST_USERS) + list(SUPPORT_USERS) + list(DEV_USERS) + list(ISHIKKI)
