from SUMI import COTB

RUN_STRINGS = (
    "Now you see me, now you don't."
    "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Save me @{COTB}"
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = (
    "CgACAgQAAxkBAAILHWBPN8dL8NvxZ9tUfr3_4SdPGqgjAAJeAgACQQrNUlM24z1ISCsTHgQ",
    "CgACAgUAAxkBAAILLWBPPY1oNbS_7IErvTnSjD-7ERotAAJVAQACbtPYVrtCdh7pOSi6HgQ",
    "CgACAgQAAxkBAAILLmBPPY7bkDGWKszfehdSJ7RpW-7vAAJoCAACVkPRUQRXQgysd04VHgQ",
) 

SLAP2_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "@{COTB} can I gban him for slapping me?"
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!"
    ])

SLAP_TEMPLATES = (
    "{user2} was killed by the Rage of @{COTB}"
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  #No game no life reference
    "Shut up {user2}, you are just {user2}.",  #No game no life reference
    "{user1} hits {user2} with Aka si anse!",  #No game no life reference
    "@NeoTheKitty scratches {user2}",  #Pixels pet cat - @NeoTheKitty 
    "Majin buu ate {user2}",  #Dbz
    "Goblin slayer slays {user2}",  #Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAAILM2BPPcztLjOKpX9lI6rqcJAf25phAAIyAgACXPW0UUEs74rXY7jHHgQ",
    "CgACAgQAAxkBAAILNGBPPc1X9A5WjSWny42TbvirITrYAAI6AgAC_hiMUsLYno0iqBsKHgQ",
    "CgACAgQAAxkBAAILNWBPPc2RwJLSld87q_QgacpiSIPoAAKFAgACa0hlUraGjbF-UlCxHgQ",
    "CgACAgQAAxkBAAILNmBPPc41VKh_5CSXiwFmLF94kt3PAAJlAgAC0xqMUgP_95WKxNyXHgQ",
    "CgACAgQAAxkBAAILN2BPPc790mPflEPaIaSLQO8UzaySAAIeAgACT3I8UIWFwhXak7MMHgQ",
    "CgACAgQAAxkBAAILOGBPPc6zjXtyaqYPS24XaWZBf51KAAJmAgACv2c9UvSqOBstdD43HgQ",
    "CgACAgQAAxkBAAILOWBPPc4bJIVehOvJ4nWEgZKiL33fAAJYAgACvTY1UhQnTgq4A5bzHgQ",
    "CgACAgQAAxkBAAILOmBPPdA2q6CUTY2Wvh147ZK5hS7fAAIiAgAClkjVUoGXNybyoMMFHgQ",
    "CgACAgQAAxkBAAILO2BPPdFcDMZLDbm2MmuHneRe72lfAAIjAgACNyiMUovAWkknFH7PHgQ",
    "CgACAgQAAxkBAAILPGBPPdHnzGgJSgxPAAF1VjxqVVgU8gACXAIAAg2OhFIv0IWYDryVzh4E",
    "CgACAgQAAxkBAAILPWBPPdE8HggjgaYISBbAXEucZ6QaAAK1AgACrxdcUkpC4d0BLZRfHgQ",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

COSPLAY = (
    "https://telegra.ph/file/0dee95b727f2028ac1856.jpg",
    "https://telegra.ph/file/c296eb3d7603a31062159.jpg",
    "https://telegra.ph/file/baddf7835b291a7fd3cfd.jpg",
    "https://telegra.ph/file/dfbf2aaa731e1cf00a2e1.jpg",
    "https://telegra.ph/file/893a0c47cec218d449965.jpg",
    "https://telegra.ph/file/5d46622a69d528737ddb9.jpg",
    "https://telegra.ph/file/7adf385229b0169c02e34.jpg",
    "https://telegra.ph/file/78ddf57462f7fa6c42ff1.jpg",
    "https://telegra.ph/file/5e599e2c0c4d3bf9788a1.jpg",
    "https://telegra.ph/file/d785a58fd84d381d79f34.jpg",
    "https://telegra.ph/file/38fafa65e89166410e71b.jpg",
    "https://telegra.ph/file/cc00468d7f06ca9be64ad.jpg",
    "https://telegra.ph/file/7f65dc3eb6938dcabe57c.jpg",
    "https://telegra.ph/file/60473963519194738eac2.jpg",
    "https://telegra.ph/file/268d07b949b32da7535de.jpg",
    "https://telegra.ph/file/89295d505cafa7de1e8a2.jpg",
    "https://telegra.ph/file/3f0490a35ae8823f0faca.jpg",
    "https://telegra.ph/file/7d580f55a513bdac0e30d.jpg",
    "https://telegra.ph/file/90b029ea381302c89aa39.jpg",
    "https://telegra.ph/file/b7340cfda5e369b03df17.jpg",
    "https://telegra.ph/file/40b6205209bbe052c30ed.jpg",
    "https://telegra.ph/file/003827e9bf30f600c133c.jpg",
    "https://telegra.ph/file/d95c170a0bb42f28f55fa.jpg",
    "https://telegra.ph/file/3347ff752fc1e99ed4f97.jpg",
    "https://telegra.ph/file/0b286c405bf999f858850.jpg",
    "https://telegra.ph/file/1c1e990e233d6f90b0298.jpg",
    "https://telegra.ph/file/2dd5ba58116101260b6f8.jpg",
    "https://telegra.ph/file/dcc3e2ab8f918b72a7e06.jpg",
    "https://telegra.ph/file/743ef4bc34d7a944b1ba7.jpg",
    "https://telegra.ph/file/8f3461fecf62b8d11823a.jpg",
    "https://telegra.ph/file/896ac9ab7486537facd5f.jpg",
    "https://telegra.ph/file/44ae9d0e02bff35850316.jpg",
    "https://telegra.ph/file/63c23b60413b06dd1b75e.jpg",
    "https://telegra.ph/file/6e220b68546b1102f748f.jpg",
    "https://telegra.ph/file/9cd29b3dfb18f7c5d6d40.jpg",
    "https://telegra.ph/file/e7d8c97856a2c52711a14.jpg",
    "https://telegra.ph/file/4c1be9254126c2398322f.jpg",
    "https://telegra.ph/file/68bac98751716c36509ce.jpg",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [['⌐■', '■'], [' ͠°', ' °'], ['⇀', '↼'], ['´• ', ' •`'], ['´', '`'],
        ['`', '´'], ['ó', 'ò'], ['ò', 'ó'], ['⸌', '⸍'], ['>',
                                                         '<'], ['Ƹ̵̡', 'Ʒ'],
        ['ᗒ', 'ᗕ'], ['⟃', '⟄'], ['⪧', '⪦'], ['⪦', '⪧'], ['⪩', '⪨'], ['⪨', '⪩'],
        ['⪰', '⪯'], ['⫑', '⫒'], ['⨴', '⨵'], ['⩿', '⪀'], ['⩾', '⩽'], ['⩺', '⩹'],
        ['⩹', '⩺'], ['◥▶', '◀◤'], ['◍', '◎'], ['/͠-', '┐͡-\\'], ['⌣', '⌣”'],
        [' ͡⎚', ' ͡⎚'], ['≋'], ['૦ઁ'], ['  ͯ'], ['  ͌'], ['ළ'], ['◉'], ['☉'],
        ['・'], ['▰'], ['ᵔ'], [' ﾟ'], ['□'], ['☼'], ['*'], ['`'], ['⚆'], ['⊜'],
        ['>'], ['❍'], ['￣'], ['─'], ['✿'], ['•'], ['T'], ['^'], ['ⱺ'], ['@'],
        ['ȍ'], ['  '], ['  '], ['x'], ['-'], ['$'], ['Ȍ'], ['ʘ'], ['Ꝋ'],
        [''], ['⸟'], ['๏'], ['ⴲ'], ['◕'], ['◔'], ['✧'], ['■'], ['♥'], [' ͡°'],
        ['¬'], [' º '], ['⨶'], ['⨱'], ['⏓'], ['⏒'], ['⍜'], ['⍤'], ['ᚖ'], ['ᴗ'],
        ['ಠ'], ['σ'], ['☯']]

MOUTHS = [['v'], ['ᴥ'], ['ᗝ'], ['Ѡ'], ['ᗜ'], ['Ꮂ'], ['ᨓ'], ['ᨎ'],
          ['ヮ'], ['╭͜ʖ╮'], [' ͟ل͜'], [' ͜ʖ'], [' ͟ʖ'], [' ʖ̯'], ['ω'], [' ³'],
          [' ε '], ['﹏'], ['□'], ['ل͜'], ['‿'], ['╭╮'], ['‿‿'], ['▾'], ['‸'],
          ['Д'], ['∀'], ['!'], ['人'], ['.'], ['ロ'], ['_'], ['෴'], ['ѽ'], ['ഌ'],
          ['⏠'], ['⏏'], ['⍊'], ['⍘'], ['ツ'], ['益'], ['╭∩╮'], ['Ĺ̯'], ['◡'],
          [' ͜つ']]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = ("Yes.", "No.", "Maybe.")


#This feature's credit goes to @ishikki_akabane
FLIRT = (
    "I hope you know CPR, because you just took my breath away!",
    "So, aside from taking my breath away, what do you do for a living?",
    "I ought to complain to Spotify for you not being named this week’s hottest single.",
    "Your eyes are like the ocean; I could swim in them all day.",
    "When I look in your eyes, I see a very kind soul.",
    "If you were a vegetable, you’d be a ‘cute-cumber.’",
    "Do you happen to have a Band-Aid? ‘Cause I scraped my knees falling for you.",
    "I never believed in love at first sight, but that was before I saw you.",
    "I didn’t know what I wanted in a woman until I saw you.",
    "You’re like a fine wine. The more of you I drink in, the better I feel.",
    "You’ve got a lot of beautiful curves, but your smile is absolutely my favorite.",
    "If being sexy was a crime, you’d be guilty as charged.",
    "I was wondering if you’re an artist because you were so good at drawing me in.",
    "It says in the Bible to only think about what’s pure and lovely… So I’ve been thinking about you all day long.",
    "Do you have a map? I just got lost in your eyes.",
    "You know what you would look really beautiful in? My arms.",
    "Are you a magician? It’s the strangest thing, but every time I look at you, everyone else disappears.",
    "I would never play hide and seek with you because someone like you is impossible to find.",
    "I think there’s something wrong with my phone. Could you try calling it to see if it works?",
    "Are you an electrician? Because you’re definitely lighting up my day/night!",
    "I always thought happiness started with an ‘h,’ but it turns out mine starts with ‘u.’",
    "I believe in following my dreams. Can I have your Instagram?",
    "If you were a song, you’d be the best track on the album.",
    "Is your name Google? Because you have everything I’m searching for.",
    "Do you ever get tired from running through my thoughts all night?",
)

SEX  = (
    "Your Di*k Is Not Long Enough.",
    "Kids Do Not Have Sex With Adults.",
    "Ohh No, You Made Her Pregnant.",
    "You're Di*kless, Try Again Later.",
    "Shut-up Small Di*k.",
    "Can You Handle My Pussy?",
    "Bring Condom First",
    "Onii-Chan, Yamete Kudasaiii...",
    "Ahhhh... Ahhhhhh... Aaahhhhhhhh...",
    "Get Lost, Horny.",
    "Tell Me Your Dad's Number, I Gotta Show This To Him.",
    "Jhaante Na Chuchi, Baatein Uchi-Uchi",
    "Masturbation Is Your Only Option.",
    "Ahhh... Not There, Ahhhhhh...",
    "Damn, why you added this command @{COTB}"
    "Save me from perverts @{COTB}"
    "I'm Ready For A White Shower, Daddy!")

HEMTAI  = (
    "• [Uncensored Hentai](https://t.me/+S6Kq1YC5bxkwZjgx0) \n• [Pornhwas](https://t.me/PornhwaHeaven)",
    "• [Uncensored Hentai](https://t.me/+S6Kq1YC5bxkwZjgx0) \n• [Pornhwas](https://t.me/PornhwaHeaven)",
    "• [Uncensored Hentai](https://t.me/+S6Kq1YC5bxkwZjgx0) \n• [Pornhwas](https://t.me/PornhwaHeaven)",)

